
export const INITIAL_LOCATION = "INITIAL_LOCATION";
export const INITIAL_LOCATION_ERROR = "INITIAL_LOCATION_ERROR";
export const LOAD_BATHROOMS = "LOAD_BATHROOMS";
export const LOAD_BATHROOMS_ERROR = "LOAD_BATHROOMS_ERROR";
export const NEW_USER = "NEW_USER";
export const NEW_USER_ERROR = "NEW_USER_ERROR";
export const STORE_PROFILE_NAME = "STORE_PROFILE_NAME"